### ISSUE TITLE
Lire Cookies dans header HTTP

### ISSUE THREAD

**Issue by GuillaumeGas** [EmileCadorel/struts-d#1]

**Comment by EmileCadorel** [comment]
ca serait bien si tu pouvais mettre de description. Le detail de ce que tu as besoin, la forme de cookies a lire ...

**Comment by GuillaumeGas** [comment]
Le but est, pour le dev, de récupérer les cookies présents dans le header HTTP facilement avec un string[string]. Pour les détails dans le protocole : 

The server sends the following in its response header to set a cookie field.

Set-Cookie:name=value

If there is a cookie set, then the browser sends the following in its request header.

Cookie:name=value

See the HTTP Cookie article at Wikipedia for more information.
https://en.wikipedia.org/wiki/HTTP_cookie

**Comment by EmileCadorel** [comment]
Done.
fd00e96f8615a9789ca4c39aa012d0f081e893e7
