### ISSUE TITLE
Chargement du manifest suite à la décompression de l'archive

### ISSUE THREAD

**Issue by TheNawaKer** [EmileCadorel/struts-d#12]
Le manifest contient:
- L'emplacement du .so
- du struts.xml

**Comment by GuillaumeGas** [comment]
C'est la même chose que l'issue #11 non?

**Comment by TheNawaKer** [comment]
Non, car ici on parle de récupérer le manifest qui contient l'emplacement des différents fichier. C'est un peu l'équivalent du manifest  sous ""Android""
L'issue #11 concerne le chargement du fichier struts.XML qui contient les différents contrôleur ...
