### ISSUE TITLE
Lire données post dans header HTTP

### ISSUE THREAD

**Issue by GuillaumeGas** [EmileCadorel/struts-d#2]

**Comment by EmileCadorel** [comment]
c.a.d ?

**Comment by GuillaumeGas** [comment]
Lien cool sur le format des données dans le header HTTP pour les données post et get : 

http://www.w3schools.com/tags/ref_httpmethods.asp

**Comment by EmileCadorel** [comment]
Done.
https://github.com/EmileCadorel/struts-d/commit/bdc64b87a7f524cd958e46c29ed2095e1ee84d95
