### ISSUE TITLE
[Erreur compile] XMLoader

### ISSUE THREAD

**Issue by GuillaumeGas** [EmileCadorel/struts-d#3]
Message d'erreur après le push d'Emile (parse d'url) :

`
source/utils/XMLoader.d:57:1: error: class utils.XMLoader.Balise use of object.Object.toString() hidden by Balise is deprecated. Use 'alias toString = Object.toString;' to introduce base class overload set.
  class Balise {
  ^

source/utils/XMLoader.d:104:1: error: class utils.XMLoader.ProcInst use of object.Object.toString() hidden by ProcInst is deprecated. Use 'alias toString = Object.toString;' to introduce base class overload se
 class ProcInst : Balise {
 ^

source/utils/XMLoader.d:110:1: error: class utils.XMLoader.Text use of object.Object.toString() hidden by Text is deprecated. Use 'alias toString = Object.toString;' to introduce base class overload set.
  class Text : Balise {
  ^
`

**Comment by GuillaumeGas** [comment]
Bon le problème vient de la surchage de toString qui semble... interdite !
Alors du coup pour les tests j'ai remplacé les déclarations de toString de Balise et et Text (qui hérite de Balise) afin que ça foute pas la merde.
A voir ce qu'il y a mieux à faire pour régler ça proprement.

**Comment by EmileCadorel** [comment]
En fait le truc c'est qu'on peut pas surcharger toString en lui passant des parametre.

ici on a 
`
string toString (int nb = 0) //c'est ce nb que gdc aime pas
`

Du coup le mieux c'est de remplacer la fonction par toStr.
