### ISSUE TITLE
[EN COURS] Prise en charge d'un fichier de config + instanciation controlleurs 

### ISSUE THREAD

**Issue by GuillaumeGas** [EmileCadorel/struts-d#4]

**Comment by GuillaumeGas** [comment]
Bon pour instancier une classe à partir d'un chaine de caractère on fait de la manière suivante : 
`A inst = cast(A)Object.factory("module_name.class_name");`

Mais ça foire quand la classe A n'est pas dans le même fichier... J'ai testé en important la classe en question et ça ne marche pas non plus. Si quelqu'un a une idée... voir sur ma branche dans sources/control/ControllerContainter.d.

**Comment by EmileCadorel** [comment]
Bon, c'est joli tout ca mais t'as oublier un detail.
Les controlleur qu'on va devoir instancier vont etre dans une 'shared library'. 
Du coup on aura pas acces au classe.

**Comment by GuillaumeGas** [comment]
On aura pas accès à quelles classes ? Les controlleurs que le dev va créer ? Si oui bah je sais bien mais du coup comment on se démerde ?^^ Ensuite va falloir appeler des méthodes de classes à partir de string aussi..

**Comment by EmileCadorel** [comment]
Bon l'histoire, La classe controleur va posseder tous plein d'instance de Controlleur deja allouer (par le chargement du .so).
Le truc ensuite c'est qu'on va les appeler avec les bonnes sessions.

**Comment by GuillaumeGas** [comment]
Le dev va devoir créer des .so ?

**Comment by EmileCadorel** [comment]
ba oui grace a l'archetype dub qu'on va lui fournir.

**Comment by GuillaumeGas** [comment]
ah okok d'où le so loader qu'il va falloir coder. Donc en gros, ça va se passer comment l'instanciation, via SoLoader ?

**Comment by EmileCadorel** [comment]
Je sais pas encore trop faut que j'y travaille.
